export const PIN_PROJECT = 'PIN_PROJECT';
export const EDIT_PROJECT = 'EDIT_PROJECT';
export const ARCHIVE_PROJECT = 'ARCHIVE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';

export const SORT_BY_PROJECT_STATUS = 'SORT_BY_PROJECT_STATUS';
export const SORT_BY_BUDGET_TYPE = 'SORT_BY_BUDGET_TYPE';
